apiVersion: v1
kind: ConfigMap
metadata:
  name: bender-config
data:
  appsettings.json: |-
{{ tpl (.Files.Get "files/appsettings.json") . | indent 4 }}
  rules.xml: |-
{{ (.Files.Get "files/rules.xml") | indent 4 }}
  crontab: |-
{{ (.Files.Get "files/crontab") | indent 4 }}
